force-app/main/default/objects/Account/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Document Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LK_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Car Registrations</relationshipLabel>
    <relationshipName>Car_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Chasis_number__c.field-meta.xml
<CustomField>
    <fullName>Chasis_number__c</fullName>
    <label>Chasis number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Car_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Car_Registration_Date__c</fullName>
    <label>Car Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Next_ITV_Revision_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Next_ITV_Revision_Date__c</fullName>
    <label>Next ITV Revision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LK_Vehicle_Owner__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>PK_Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diesel Oil</fullName>
            </value>
            <value>
                <fullName>Fuel Oil</fullName>
            </value>
            <value>
                <fullName>Solar Oil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Brand__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Brand__c</fullName>
    <label>Vehicle Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PK_Vehicle_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILX</fullName>
            </value>
            <value>
                <fullName>MDX</fullName>
            </value>
            <value>
                <fullName>MDX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>NSX</fullName>
            </value>
            <value>
                <fullName>RDX</fullName>
            </value>
            <value>
                <fullName>RLX</fullName>
            </value>
            <value>
                <fullName>RLX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>TLX</fullName>
            </value>
            <value>
                <fullName>4C Spider</fullName>
            </value>
            <value>
                <fullName>Giulia</fullName>
            </value>
            <value>
                <fullName>Stelvio</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A6 allroad</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q5</fullName>
            </value>
            <value>
                <fullName>Q7</fullName>
            </value>
            <value>
                <fullName>Q8</fullName>
            </value>
            <value>
                <fullName>R8</fullName>
            </value>
            <value>
                <fullName>S4</fullName>
            </value>
            <value>
                <fullName>S8</fullName>
            </value>
            <value>
                <fullName>SQ5</fullName>
            </value>
            <value>
                <fullName>TT</fullName>
            </value>
            <value>
                <fullName>2 Series</fullName>
            </value>
            <value>
                <fullName>3 Series</fullName>
            </value>
            <value>
                <fullName>4 Series</fullName>
            </value>
            <value>
                <fullName>5 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/TX_Car_Number_Plate__c.field-meta.xml
<CustomField>
    <fullName>TX_Car_Number_Plate__c</fullName>
    <label>Car Number Plate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Vehicle_Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>FIAT</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Freightliner</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>INFINITI</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>MAZDA</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes-Benz</fullName>
    </customValue>
    <customValue>
        <fullName>MINI</fullName>
    </customValue>
    <customValue>
        <fullName>Mitsubishi</fullName>
    </customValue>
    <customValue>
        <fullName>Nissan</fullName>
    </customValue>
    <customValue>
        <fullName>Porsche</fullName>
    </customValue>
    <customValue>
        <fullName>Ram</fullName>
    </customValue>
    <masterLabel>Vehicle Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerTest.cls
@isTest
public class CustomerTest{
    
    @isTest
    static void customerCreationTest() {
        Account a = new Account();
        //a.RecordTypeId = personAccountRT;
        a.FirstName = 'Account Prueba';
        a.LastName = 'Apellidos Prueba';
        a.BillingStreet = 'Calle Inventada';
        a.BillingCity = 'Santander';
        a.BillingCountry = 'Spain';
        a.Phone = '633445533';
        a.PersonHomePhone = '942333333';
        a.PersonEmail = 'prueba@prueba.com';
        a.Document_Number__c = '76655443H';
        
       	Test.startTest();
        insert a;
        Test.stopTest();
    }
    
    
    @isTest
    static void deleteAccountWithActiveReceptionsTest() {
        Account a = new Account();
        //a.RecordTypeId = personAccountRT;
        a.FirstName = 'Account Prueba';
        a.LastName = 'Apellidos Prueba';
        a.BillingStreet = 'Calle Inventada';
        a.BillingCity = 'Santander';
        a.BillingCountry = 'Spain';
        a.Phone = '633445533';
        a.PersonHomePhone = '942333333';
        a.PersonEmail = 'prueba@prueba.com';
        a.Document_Number__c = '76655443H';
        insert a;
        
        Account a1 = [SELECT Id from Account limit 1];
        
        Vehicle__c v = new Vehicle__c();
        v.Name = 'Test1';
        v.Chasis_number__c = '465859845';
        v.DT_Car_Registration_Date__c = Date.today();
        v.DT_Next_ITV_Revision_Date__c = Date.today().addDays(40);
        v.PK_Fuel_Type__c = 'Fuel Oil';
        v.PK_Vehicle_Brand__c = 'BMW';
        v.PK_Vehicle_Model__c = '2 Series';
        v.TX_Car_Number_Plate__c = '4321HTT';
        v.LK_Vehicle_Owner__c = a1.Id;
        insert v;
        
        Vehicle__c v1 = [SELECT Id FROM Vehicle__c LIMIT 1];
        
        Opportunity r = new Opportunity();
        r.Name = 'Reception Test';
        r.AccountId = a1.Id;
        r.StageName ='Needs analysis';
        r.LK_Vehicle__c = v1.Id;
        r.CloseDate = Date.newInstance(2024,06,22);
        insert r;
        
       	Test.startTest();
        
        delete a1;
        
        Test.stopTest();
    }

}