force-app/main/default/objects/Account/fields/Document_Number__c.field-meta.xml
<CustomField>
    <fullName>Document_Number__c</fullName>
    <label>Document Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LK_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Car Registrations</relationshipLabel>
    <relationshipName>Car_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cuenta personal</label>
</RecordType>

force-app/main/default/objects/Service_monitoring__c/Service_monitoring__c.object-meta.xml
<CustomObject>
    <label>Work Status</label>
    <nameField>
        <label>Service Monitoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_monitoring__c/fields/Related_reception_service__c.field-meta.xml
<CustomField>
    <fullName>Related_reception_service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related reception of service</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Statuses (Related reception of service)</relationshipLabel>
    <relationshipName>Work_Statuses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Chasis_number__c.field-meta.xml
<CustomField>
    <fullName>Chasis_number__c</fullName>
    <label>Chasis number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Car_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Car_Registration_Date__c</fullName>
    <label>Car Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Next_ITV_Revision_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Next_ITV_Revision_Date__c</fullName>
    <label>Next ITV Revision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LK_Vehicle_Owner__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>PK_Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diesel Oil</fullName>
            </value>
            <value>
                <fullName>Fuel Oil</fullName>
            </value>
            <value>
                <fullName>Solar Oil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Brand__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Brand__c</fullName>
    <label>Vehicle Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PK_Vehicle_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILX</fullName>
            </value>
            <value>
                <fullName>MDX</fullName>
            </value>
            <value>
                <fullName>MDX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>NSX</fullName>
            </value>
            <value>
                <fullName>RDX</fullName>
            </value>
            <value>
                <fullName>RLX</fullName>
            </value>
            <value>
                <fullName>RLX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>TLX</fullName>
            </value>
            <value>
                <fullName>4C Spider</fullName>
            </value>
            <value>
                <fullName>Giulia</fullName>
            </value>
            <value>
                <fullName>Stelvio</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A6 allroad</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q5</fullName>
            </value>
            <value>
                <fullName>Q7</fullName>
            </value>
            <value>
                <fullName>Q8</fullName>
            </value>
            <value>
                <fullName>R8</fullName>
            </value>
            <value>
                <fullName>S4</fullName>
            </value>
            <value>
                <fullName>S8</fullName>
            </value>
            <value>
                <fullName>SQ5</fullName>
            </value>
            <value>
                <fullName>TT</fullName>
            </value>
            <value>
                <fullName>2 Series</fullName>
            </value>
            <value>
                <fullName>3 Series</fullName>
            </value>
            <value>
                <fullName>4 Series</fullName>
            </value>
            <value>
                <fullName>5 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/TX_Car_Number_Plate__c.field-meta.xml
<CustomField>
    <fullName>TX_Car_Number_Plate__c</fullName>
    <label>Car Number Plate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Vehicle_Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>FIAT</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Freightliner</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>INFINITI</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>MAZDA</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes-Benz</fullName>
    </customValue>
    <customValue>
        <fullName>MINI</fullName>
    </customValue>
    <customValue>
        <fullName>Mitsubishi</fullName>
    </customValue>
    <customValue>
        <fullName>Nissan</fullName>
    </customValue>
    <customValue>
        <fullName>Porsche</fullName>
    </customValue>
    <customValue>
        <fullName>Ram</fullName>
    </customValue>
    <masterLabel>Vehicle Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReceptionTest.cls
@isTest
public class ReceptionTest {
    
    @isTest
    static void receptionCreationCloseDateTest(){
        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        // Create an account.
        Account a = new Account();
        a.FirstName = 'Account Prueba';
        a.LastName = 'Apellidos Prueba';
        a.BillingStreet = 'Calle Inventada';
        a.BillingCity = 'Santander';
        a.BillingCountry = 'Spain';
        a.Phone = '633445533';
        a.PersonHomePhone = '942333333';
        a.PersonEmail = 'prueba@prueba.com';
        a.Document_Number__c = '76655443H';
        a.recordTypeId = personAccountRecordTypeId;
        insert a;
        
        Account a1 = [SELECT Id from Account limit 1];
        
        // Create a vehicle.
        Vehicle__c v = new Vehicle__c();
        v.Name = 'Test1';
        v.Chasis_number__c = '465859845';
        v.DT_Car_Registration_Date__c = Date.today();
        v.DT_Next_ITV_Revision_Date__c = Date.today().addDays(40);
        v.PK_Fuel_Type__c = 'Fuel Oil';
        v.PK_Vehicle_Brand__c = 'BMW';
        v.PK_Vehicle_Model__c = '2 Series';
        v.TX_Car_Number_Plate__c = '4321HTT';
        v.LK_Vehicle_Owner__c = a1.Id;
        insert v;
        
        Vehicle__c v1 = [SELECT Id FROM Vehicle__c LIMIT 1];
        
        // Create an opportunity.
        Opportunity r = new Opportunity();
        r.Name = 'Reception Test';
        r.AccountId = a1.Id;
        r.StageName ='Making budget';
        r.LK_Vehicle__c = v1.Id;
        insert r;
        
        //  Perform a query after insertion.
        Opportunity opp = [SELECT Id, Name, CloseDate FROM Opportunity WHERE Id = :r.Id];
        
        // It checks that the CloseDate field matches the current date + 1 year.
		System.assertEquals(Date.today().AddDays(365), opp.CloseDate, 'The CloseDate field does not have the correct value.');

    }
    
    @isTest
	static void receptionCreationEmailTest(){
		
        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        // Create an account.
        Account acc = new Account();
        acc.FirstName = 'Account Prueba 2';
        acc.LastName = 'Apellidos Prueba 2';
        acc.BillingStreet = 'Calle Inventada 2';
        acc.BillingCity = 'Santander';
        acc.BillingCountry = 'Spain';
        acc.Phone = '633445533';
        acc.PersonHomePhone = '942333333';
        acc.PersonEmail = 'prueba2@prueba.com';
        acc.Document_Number__c = '76655443H';
        acc.recordTypeId = personAccountRecordTypeId;
        insert acc;
        
        // Create a vehicle.
        Vehicle__c veh = new Vehicle__c();
        veh.Name = 'Test 2';
        veh.Chasis_number__c = '465859845';
        veh.DT_Car_Registration_Date__c = Date.today();
        veh.DT_Next_ITV_Revision_Date__c = Date.today().addDays(40);
        veh.PK_Fuel_Type__c = 'Fuel Oil';
        veh.PK_Vehicle_Brand__c = 'BMW';
        veh.PK_Vehicle_Model__c = '2 Series';
        veh.TX_Car_Number_Plate__c = '4321HTT';
        veh.LK_Vehicle_Owner__c = acc.Id;
        insert veh;

        // Create a contact associated with the account.
    	Contact con = new Contact();
    	con.FirstName = 'Nombre de Prueba';
    	con.LastName = 'Apellidos de Prueba';
    	con.Email = 'prueba2@prueba.com';
    	insert con;
        
        // Create an opportunity.
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Reception Test';
        opp2.AccountId = acc.Id;
        opp2.StageName ='Making budget';
        opp2.LK_Vehicle__c = veh.Id;
        insert opp2;
        
    	// Create an email.
    	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
    	email.setTargetObjectId(con.Id);
    	email.setSubject('Correo de prueba');
    	email.setPlainTextBody('Este es un correo de prueba.');

    	// Send the email.
   	 	Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});

    	// Check if the email was sent correctly.
    	System.assert(results[0].isSuccess(), 'El correo no se envió correctamente.');
	}
    
    @isTest
    static void receptionDeleteWorkStatusTest(){

        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        // Create an account.
        Account acc3 = new Account();
        acc3.FirstName = 'Account Prueba 3';
        acc3.LastName = 'Apellidos Prueba 3';
        acc3.BillingStreet = 'Calle Inventada 3';
        acc3.BillingCity = 'Santander';
        acc3.BillingCountry = 'Spain';
        acc3.Phone = '633445533';
        acc3.PersonHomePhone = '942333333';
        acc3.PersonEmail = 'prueba2@prueba.com';
        acc3.Document_Number__c = '76655443H';
        acc3.recordTypeId = personAccountRecordTypeId;
        insert acc3;
        
        // Create a vehicle.
        Vehicle__c veh3 = new Vehicle__c();
        veh3.Name = 'Test 3';
        veh3.Chasis_number__c = '465859845';
        veh3.DT_Car_Registration_Date__c = Date.today();
        veh3.DT_Next_ITV_Revision_Date__c = Date.today().addDays(40);
        veh3.PK_Fuel_Type__c = 'Fuel Oil';
        veh3.PK_Vehicle_Brand__c = 'BMW';
        veh3.PK_Vehicle_Model__c = '2 Series';
        veh3.TX_Car_Number_Plate__c = '4321HTT';
        veh3.LK_Vehicle_Owner__c = acc3.Id;
        insert veh3;
        
        // Create an opportunity.
        Opportunity opp3 = new Opportunity();
        opp3.Name = 'Reception Test 3';
        opp3.AccountId = acc3.Id;
        opp3.StageName ='Making budget';
        opp3.LK_Vehicle__c = veh3.Id;
        insert opp3;        
        
        // Create Work Status (Service_monitoring__c).
        Service_monitoring__c ser = new Service_monitoring__c();
        ser.Name = 'Test 3 Service';
        ser.Related_reception_service__c = opp3.Id;
        insert ser;

        // Remove the opportunity.
        delete opp3;

    	// Verify if the Service_monitoring__c record has also been deleted.
    	try {
        	Service_monitoring__c deletedSer = [SELECT Id FROM Service_monitoring__c WHERE Related_reception_service__c = :opp3.Id LIMIT 1];
        	System.assert(deletedSer == null, 'The Service_monitoring__c record was not deleted correctly.');
   	 	} catch (QueryException e) {
        	System.debug('No Service_monitoring__c record found. This is expected.');
    		}  
    }
}