force-app/main/default/objects/Opportunity/fields/LK_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Car Registrations</relationshipLabel>
    <relationshipName>Car_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cuenta personal</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Required_materials__c.field-meta.xml
<CustomField>
    <fullName>Required_materials__c</fullName>
    <label>Required materials</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Chasis_number__c.field-meta.xml
<CustomField>
    <fullName>Chasis_number__c</fullName>
    <label>Chasis number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Car_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Car_Registration_Date__c</fullName>
    <label>Car Registration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/DT_Next_ITV_Revision_Date__c.field-meta.xml
<CustomField>
    <fullName>DT_Next_ITV_Revision_Date__c</fullName>
    <label>Next ITV Revision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LK_Vehicle_Owner__c.field-meta.xml
<CustomField>
    <fullName>LK_Vehicle_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vehicle Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>PK_Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diesel Oil</fullName>
            </value>
            <value>
                <fullName>Fuel Oil</fullName>
            </value>
            <value>
                <fullName>Solar Oil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Brand__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Brand__c</fullName>
    <label>Vehicle Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/PK_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>PK_Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PK_Vehicle_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILX</fullName>
            </value>
            <value>
                <fullName>MDX</fullName>
            </value>
            <value>
                <fullName>MDX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>NSX</fullName>
            </value>
            <value>
                <fullName>RDX</fullName>
            </value>
            <value>
                <fullName>RLX</fullName>
            </value>
            <value>
                <fullName>RLX Sport Hybrid</fullName>
            </value>
            <value>
                <fullName>TLX</fullName>
            </value>
            <value>
                <fullName>4C Spider</fullName>
            </value>
            <value>
                <fullName>Giulia</fullName>
            </value>
            <value>
                <fullName>Stelvio</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A6 allroad</fullName>
            </value>
            <value>
                <fullName>A7</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q5</fullName>
            </value>
            <value>
                <fullName>Q7</fullName>
            </value>
            <value>
                <fullName>Q8</fullName>
            </value>
            <value>
                <fullName>R8</fullName>
            </value>
            <value>
                <fullName>S4</fullName>
            </value>
            <value>
                <fullName>S8</fullName>
            </value>
            <value>
                <fullName>SQ5</fullName>
            </value>
            <value>
                <fullName>TT</fullName>
            </value>
            <value>
                <fullName>2 Series</fullName>
            </value>
            <value>
                <fullName>3 Series</fullName>
            </value>
            <value>
                <fullName>4 Series</fullName>
            </value>
            <value>
                <fullName>5 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/TX_Car_Number_Plate__c.field-meta.xml
<CustomField>
    <fullName>TX_Car_Number_Plate__c</fullName>
    <label>Car Number Plate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Vehicle_Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chevrolet</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>FIAT</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Freightliner</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>INFINITI</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>MAZDA</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes-Benz</fullName>
    </customValue>
    <customValue>
        <fullName>MINI</fullName>
    </customValue>
    <customValue>
        <fullName>Mitsubishi</fullName>
    </customValue>
    <customValue>
        <fullName>Nissan</fullName>
    </customValue>
    <customValue>
        <fullName>Porsche</fullName>
    </customValue>
    <customValue>
        <fullName>Ram</fullName>
    </customValue>
    <masterLabel>Vehicle Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TallercanUtilsTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-30-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class TallercanUtilsTest {
    
    @testSetup
    static void setupTestData() {

        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

        Account newPersonAccount = new Account();
        // Create test Account
        Account acc = new Account(FirstName = 'Test Account', LastName = 'Test', recordTypeId = personAccountRecordTypeId);
        insert acc;
        Account a = [SELECT Id from Account LIMIT 1];

       
        Vehicle__c v = new Vehicle__c();
        v.Name = 'Test1';
        v.Chasis_number__c = '465859845';
        v.DT_Car_Registration_Date__c = Date.today();
        v.DT_Next_ITV_Revision_Date__c = Date.today().addDays(40);
        v.PK_Fuel_Type__c = 'Fuel Oil';
        v.PK_Vehicle_Brand__c = 'BMW';
        v.PK_Vehicle_Model__c = '2 Series';
        v.TX_Car_Number_Plate__c = '4321HTT';
        v.LK_Vehicle_Owner__c = a.Id;

        // Create test Opportunity (reception)
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = acc.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            LK_Vehicle__c = v.Id,
            StageName  = 'Created',
            Reception_Date__c = Date.today()
        );
        insert opp;

        // Create test Products
        Product2 prod1 = new Product2(Name = 'Product 1', IsActive = true, Required_materials__c = 'Material1');
        Product2 prod2 = new Product2(Name = 'Product 2', IsActive = true, Required_materials__c = 'Material2');
        insert new List<Product2> { prod1, prod2 };

        // Create Pricebook
        Pricebook2 standardPricebook = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        
        // Create Pricebook Entries
        PricebookEntry pbe1 = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id, Product2Id = prod1.Id, UnitPrice = 100, IsActive = true
        );
        PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id, Product2Id = prod2.Id, UnitPrice = 200, IsActive = true
        );
        insert new List<PricebookEntry> { pbe1, pbe2 };
    }
    
    @isTest
    static void testCreateRelatedQuotesByCategory() {
        // Retrieve test data
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Product2 prod1 = [SELECT Id FROM Product2 WHERE Name = 'Product 1' LIMIT 1];
        Product2 prod2 = [SELECT Id FROM Product2 WHERE Name = 'Product 2' LIMIT 1];
        
        // Create request object
        TallercanUtils.Request request = new TallercanUtils.Request();
        request.receptionId = opp.Id;
        request.category = 'Standard';
        request.servicesObject = new List<Product2> { prod1, prod2 };
        
        List<TallercanUtils.Request> requests = new List<TallercanUtils.Request> { request };

        // Test the createRelatedQuotesByCategory method
        Test.startTest();
        TallercanUtils.createRelatedQuotesByCategory(requests);
        Test.stopTest();
        
        // Verify OpportunityLineItems creation
        List<OpportunityLineItem> oppLineItems = [SELECT Id, OpportunityId, Product2Id, Quantity, UnitPrice FROM OpportunityLineItem WHERE OpportunityId = :opp.Id];
        System.assertEquals(2, oppLineItems.size(), 'There should be 2 OpportunityLineItems');
        
        // Verify details of the created line items
        OpportunityLineItem oli1 = oppLineItems[0];
        OpportunityLineItem oli2 = oppLineItems[1];
        
        System.assertEquals(opp.Id, oli1.OpportunityId, 'OpportunityId should match the provided Opportunity Id');
        System.assertEquals(opp.Id, oli2.OpportunityId, 'OpportunityId should match the provided Opportunity Id');
        
        System.assertEquals(prod1.Id, oli1.Product2Id, 'First OpportunityLineItem should be for Product 1');
        System.assertEquals(prod2.Id, oli2.Product2Id, 'Second OpportunityLineItem should be for Product 2');
        
        System.assertEquals(1, oli1.Quantity, 'Quantity should be 1 for the first item');
        System.assertEquals(1, oli2.Quantity, 'Quantity should be 1 for the second item');
        
        System.assertEquals(100, oli1.UnitPrice, 'UnitPrice should be 100 for the first item');
        System.assertEquals(200, oli2.UnitPrice, 'UnitPrice should be 200 for the second item');
    }
}